<html>
	<head>
		<meta charset="utf-8" />
		<title>Miniframework</title>

		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
		<style>

			body{
				min-height: 100vh;
				display: flex;
				flex-direction: column;
			}

			main{
				width: 100%;
				flex-grow: 1;
				padding: 10px;
			}

			footer{
				background: #333;
				height: 100px;
			}
		
		
		</style>
	</head>

	<body>

		<nav class="navbar navbar-dark bg-dark" style = "color: #fff;">
			<div class="container-fluid">
				<a class="navbar-brand">TESTE#1 - MVC </a>
				<form class="d-flex">
				<input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
				<button class="btn btn-outline-success" type="submit">Search</button>
				</form>
			</div>
		</nav>

		<main>

			<!-- Conteúdo da view -->
			<?= $this->content() ?>
		
		</main>

		<footer>
			<p></p>
		</footer>

	</body>

</html>