<div class = "table_container">
    <div class = "header_container">
        <h2>Página home | User ID: <?php echo $_GET["userid"] ?></h2>
    </div>
    <div class = "body_container">
        <table class="table">
            <thead>
                <tr>
                <th scope="col">ID</th>
                <th scope="col">Email</th>
                <th scope="col">Username</th>
                <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php echo $this->tableData; ?>
            </tbody>
        </table>
    </div>
</div>







