<h2>Alterar a senha</h2>

<form class = "outside_form" method = "POST" action = "/sendcode">
    <div class = "form_row">
        <label for = "send_code_email">Informe o seu e-mail</label>
        <input type = "email" name = "send_code_email" id = "send_code_email">
    </div>
    <div class = "submit_row">
        <input type = "submit" name = "send_code_button" value = "Receber código">
    </div>
</form>

<hr>

<form class = "outside_form" method = "POST" action = "/dopasswordchange">
    <div class = "form_row">
        <label for = "email_code">Informe o código recebido</label>
        <input type = "text" name = "email_code" id = "email_code" disabled>
    </div>
    <div class = "form_row">
        <label for = "new_password">Nova senha</label>
        <input type = "password" name = "new_password" id = "new_password" disabled>
    </div>
    <div class = "submit_row">
        <input type = "submit" name = "change_password_button" value = "Confirmar" disabled>
    </div>
</form>

<hr>
<nav>
    <p><a href = "/registration">Não é membro? Realize o seu registro!</a></p>
    <p><a href = "/change_password">Esqueceu a senha?</a></p>
</nav>



