<h2>Página de login</h2>

<form class = "outside_form" method = "POST" action = "/doaccess">
    <div class = "form_row">
        <label for = "login_username">Informe o nome de usuário</label>
        <input type = "text" name = "login_username" id = "login_username">
    </div>
    <div class = "form_row">
        <label for = "login_password">Informe a senha</label>
        <input type = "password" name = "login_password" id = "login_password">
    </div>
    <div class = "submit_row">
        <input type = "submit" name = "login_button" value = "Acessar">
    </div>
</form>

<hr>
<nav>
    <p><a href = "/registration">Não está registrado?</a></p>
    <p><a href = "/change_password">Esqueceu a senha?</a></p>
</nav>



