<?php session_start(); ?>

<h2>Página de registro</h2>

<form class = "outside_form" method = "POST" action = "/doregister">
    <div class = "form_row" method = "POST">
        <label for = "registration_email">Informe o seu e-mail</label>
        <input type = "email" name = "registration_email" id = "registration_email">
    </div>
    <div class = "form_row">
        <label for = "registration_username">Escolha um nome de usuário</label>
        <input type = "text" name = "registration_username" id = "registration_username">
    </div>
    <div class = "form_row">
        <label for = "registration_password">Escolha uma senha</label>
        <input type = "text" name = "registration_password" id = "registration_password">
    </div>
    <div class = "submit_row">
        <input type = "submit" name = "registration_button" value = "Registrar">
    </div>
    <div class = "form_row">
        <?php if(isset($_SESSION["operation"])){echo $_SESSION["operation"]; unset($_SESSION["operation"]);}?>
    </div>
</form>

<hr>
<nav>
    <p><a href = "/login">Acessar</a></p>
</nav>





