<h1>Index</h1>
<p><a href="./contato">Página de contato</a></p>
<hr/>

<?php

	$tr_list = '';
	foreach($this->view->dados as $row => $record){

		$tr_list .= "<tr>
				<th scope='row'>{$record['id']}</th>
				<td>{$record['descricao']}</td>
				<td>{$record['preco']}</td>
				</tr>";

	}

?>

<table class="table">
  <thead>
      <th scope="col">ID</th>
      <th scope="col">Descrição</th>
      <th scope="col">Preço</th>
    </tr>
  </thead>
  <tbody>
	<?php
	echo $tr_list;
	?>
  </tbody>
</table>


	