<nav>
    <p><a href = "/system/dashboard" style = "color: #333;">Index</a> / <a href = "/system/newproduct">Novo Produto</a></p>
</nav>
<hr>

<p>DASHBOARD</p>

<?php

    // StdClass do Action.php
    // É construído dinâmicamente no contralador da rota
    echo $this->viewData->dbMessage;

    $table = "
        <table>
        <tbhead>
            <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>Preço</th>
            </tr>
        </tbhead>
        <tbody>";

    foreach($this->viewData->dbData as $key => $value){

        $table .= "
            <tr>
                <td>{$value['id']}</td>
                <td>{$value['name']}</td>
                <td>R\$ {$value['price']}</td>
            </tr>
        ";
        
    }

    $table .= "
            </tbody>
        </table>
    ";

    echo $table;

?>

<p><a href = "/">Sair</a></p>